#!/bin/bash


# convert all markdown files to html
options=(--shift-heading-level-by=1 --highlight-style monochrome) 
genhtml(){
   for file in ./blog/posts/*.md; do
       [ -e "$file" ] || continue
       pandoc metadata.yaml "${options[@]}" -s "$file" -o blog/"$(basename "$file" .md)".html 
   done
}

genblogindex(){
    rm -f blog/index.html
    title="    Lawrence Logoh's Blog"
    include_after="include-after: '<a href=\"https://www.lawrencelogoh.xyz\"><- Back to home</a>'"
    printf "%s\n" "---" "title: > " "$title" "$include_after"  "---" > blog/posts/index.md
    items=()
    for file in ./blog/*.html; do
	[ -e "$file" ] || continue
	title=$(pup -f "$file" title text{})
	
	prefix="https://www.lawrencelogoh.xyz/blog/"
	link="- [$title]($prefix$(basename "$file" ))"
	items=(${items[@]} $link)
    done
    
    items=($(sort -n <<<"${items[*]}"))
    
    for value in "${items[@]}"; do
	echo "$value" >> blog/posts/index.md 
    done
    echo "${items[*]}"
		 
}


genothers(){
    pandoc metadata.yaml "${options[@]}" -s index.md -o index.html
    pandoc metadata.yaml "${options[@]}" -s donate/index.md -o donate/index.html
    pandoc metadata.yaml "${options[@]}" -s about/index.md -o about/index.html 
    
}



rm -f ./blog/*.html
genhtml
genblogindex
genhtml # shouldn't be doing this twice
genothers



#genrss

# Generate rss feed
