#!/usr/bin/env bash


openring \
    -s https://ariadnavigo.xyz/posts/index.xml \
    -s https://drewdevault.com/feed.xml \
    -s https://protesilaos.com/master.xml \
    -s https://geohot.github.io/blog/feed.xml \
    < static/wr_template.html \
    > static/webring.html 
