#+TITLE: 2024 Review
#+DATE: 2024-12-31
#+AUTHOR: Lawrence Logoh
#+OPTIONS: toc:nil num:nil

The general plan this year was to get good. I made detailed plans that I
followed to the best of my ability but unfortunately, I didn't reach
most of my goals. I bit off more than I could chew.

* Health
I created a workout routine and made time for it.
The problem was, I had to actually workout.
I worked out sometimes but most of the time I didn't.
Mentally, I'm doing better than I was last year.
I'm less anxious and my baseline happiness is still high so I'm good on
this front.

* Productivity
The goal was to create habits that will make me more productive.
I definitely created habits.
The problem was, I created too much.
This led to me not following them at all in some cases.
It's an improvement from last year but I could have been better.

* Programming
I feel like I got better at programming, but I don't have much to show
for it.
I don't remember how many personal projects I started but I didn't
finish any of them.

* Money
I made more money this year than I did last year.
I didn't get to an average of $2000 a month but it's an improvement.
One thing I decided halfway through the year was to stop talking about
money.
I've found that people get really weird when money comes up so for now
I won't be talking about concrete numbers.

* Relationships
I made some new friends this year and I put more effort into maintaining
the relationships that I have.
Still no dice in the romantic department but I'll keep trying.

* Knowledge
I learned a lot about a lot of different things. I also made some
decisions on how I'm going to document some of these things.
Most of them will go into my zettelkasten but for other things they will
go into my Knowledge Management System.

* Skills
The goal here was to focus on Graphic Design and UI/UX.
I tried to do too much here and I've learned my lesson.
I'm going to take it one at a time from now on.

* Conclusion
This was a good year.
I didn't do everything I wanted to but I've learned a lot about myself
and I'm going to try to work with what I have instead of trying to
brute force everything.
