#+TITLE: Everything Matters
#+DATE: 2026-05-24
#+AUTHOR: Lawrence Logoh
#+OPTIONS: toc:nil num:nil

In March of 2023, I started working at Blue Torus.
If I had to describe myself back then I would say I was very
"engineer-brained".
What I mean is, I only cared if something worked.
Aesthetics didn't matter that much to me.

I consider myself a pretty smart guy.
I don't often meet people who I think are smarter than me.
Tim, my team lead, was the first person I met in real life who I thought was
legitimately smarter than me.
He also cared a lot about aesthetics, which I found strange at the time.

Tim would give me tasks that I would complete in my "engineer-brained"
way and then Tim would explain how I could improve it. I didn't always
get it and in the beginning I didn't think it mattered. 
Over time, I think I've developed my own sense of what I think good
aesthetics are and now I see aesthetics everywhere.

I see it when I look at this website, when I watch a YouTube video or
even when I read an email.
I'm still a little "engineer-brained" but I think the aesthetics matter
a lot.

I'm a firm believer in "how you do one thing is how you do everything"
and I'm trying to incorporate my newfound love of aesthetics into
everything.

In how I program, how I express myself, how I work with others, in my
fashion sense, in the things I buy, et cetera, et cetera.


I'm taking it one step at a time though, so don't expect any big changes XD.
